[package]
name = "agent_wire"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = "0.19.4"
prost = "0.14.1"
prost-types = { version = "0.14.1", features = ["chrono"] }

[build-dependencies]
prost-build = "0.14.1"
